// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: XOErrorCode.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from XOErrorCode.proto</summary>
public static partial class XOErrorCodeReflection {

  #region Descriptor
  /// <summary>File descriptor for XOErrorCode.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static XOErrorCodeReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFYT0Vycm9yQ29kZS5wcm90byqPBQoJRXJyb3JDb2RlEgwKCE5PX0VSUk9S",
          "EAASEQoNSU5WQUxJRF9QQVJBTRAFEhkKFUlOVEVSX0VSUk9SX1VOQ0FUQ0hF",
          "RBBkEhoKFklOVEVSX0VSUk9SX05PX0hBTkRMRVIQZRIOCgpFUlJPUl9BVVRI",
          "EGYSEwoPQ09ORElUSU9OX0VSUk9SEGcSFQoRQ09OVEVOVF9TRU5TSVRJVkUQ",
          "aRIaChZDT05URU5UX1RPT19MT05HX0VSUk9SEGoSFAoQQ09ORklHX05PVF9F",
          "UlJPUhBrEhgKE1VTRVJfTklDS05BTUVfRVhJU1QQ6QcSFgoRVVNFUk5BTUVf",
          "UFJPSElCSVQQ6gcSFAoPVVNFUl9OT1RfRVhJU1RTEOsHEhQKD1VTRVJfTk9U",
          "X0NSRUFURRDsBxIUCg9VU0VSX1NUQVRVU19CQU4Q7QcSGAoTVVNFUl9ST09N",
          "X05PVF9FWElTVBDuBxIVChBVU0VSX1JPT01fTk9UX0lOEO8HEhgKE1VTRVJf",
          "Uk9PTV9OT1RfT1dORVIQ8AcSHQoYR0FNRV9BTkNIT1JfU1RBVFVTX0VSUk9S",
          "EM0IEhQKD0dBTUVfUk9PTV9FUlJPUhDOCBIUCg9HQU1FX1VTRVJfTk9USU4Q",
          "zwgSHQoYR0FNRV9VU0VSX1dJTl9OT1RfRU5PVUdIENAIEhgKE0xVQ0tfTU9E",
          "RV9OT1RfRVhJU1QQ0QgSGgoVR0FNRV9NT05FWV9OT1RfRU5PVUdIENIIEh8K",
          "GkdBTUVfQ0FUQ0hfRklTSF9OT1RfRU5PVUdIENMIEg0KCERZX0VSUk9SELEJ",
          "EhUKEERZX1dFQkNBU1RfRVJST1IQsgkSFgoRVEFTS19TVEFUVVNfRVJST1IQ",
          "lQpCHwoUY29tLnR3eC5vcmlnaW4ucHJvdG9CB1hPRXJyb3JiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ErrorCode), }, null, null));
  }
  #endregion

}
#region Enums
public enum ErrorCode {
  /// <summary>
  /// 返回没有错误发生
  /// </summary>
  [pbr::OriginalName("NO_ERROR")] NoError = 0,
  /// <summary>
  /// 无效的参数
  /// </summary>
  [pbr::OriginalName("INVALID_PARAM")] InvalidParam = 5,
  /// <summary>
  /// 内部错误：100
  /// </summary>
  [pbr::OriginalName("INTER_ERROR_UNCATCHED")] InterErrorUncatched = 100,
  /// <summary>
  /// 没有这个handler
  /// </summary>
  [pbr::OriginalName("INTER_ERROR_NO_HANDLER")] InterErrorNoHandler = 101,
  /// <summary>
  /// 认证错误
  /// </summary>
  [pbr::OriginalName("ERROR_AUTH")] ErrorAuth = 102,
  /// <summary>
  /// 条件错误,客户端有误,请参考接口文档
  /// </summary>
  [pbr::OriginalName("CONDITION_ERROR")] ConditionError = 103,
  /// <summary>
  ///	内容包含敏感字符
  /// </summary>
  [pbr::OriginalName("CONTENT_SENSITIVE")] ContentSensitive = 105,
  /// <summary>
  /// 内容过长
  /// </summary>
  [pbr::OriginalName("CONTENT_TOO_LONG_ERROR")] ContentTooLongError = 106,
  /// <summary>
  /// 服务器缺少必要配置参数
  /// </summary>
  [pbr::OriginalName("CONFIG_NOT_ERROR")] ConfigNotError = 107,
  /// <summary>
  ///user 1001~1100
  /// </summary>
  [pbr::OriginalName("USER_NICKNAME_EXIST")] UserNicknameExist = 1001,
  /// <summary>
  /// 昵称不合规
  /// </summary>
  [pbr::OriginalName("USERNAME_PROHIBIT")] UsernameProhibit = 1002,
  /// <summary>
  /// 用户不存在
  /// </summary>
  [pbr::OriginalName("USER_NOT_EXISTS")] UserNotExists = 1003,
  /// <summary>
  /// 角色还未创建
  /// </summary>
  [pbr::OriginalName("USER_NOT_CREATE")] UserNotCreate = 1004,
  /// <summary>
  /// </summary>
  [pbr::OriginalName("USER_STATUS_BAN")] UserStatusBan = 1005,
  /// <summary>
  /// 房间不存在
  /// </summary>
  [pbr::OriginalName("USER_ROOM_NOT_EXIST")] UserRoomNotExist = 1006,
  /// <summary>
  /// 不在房间中
  /// </summary>
  [pbr::OriginalName("USER_ROOM_NOT_IN")] UserRoomNotIn = 1007,
  /// <summary>
  /// 不是房主
  /// </summary>
  [pbr::OriginalName("USER_ROOM_NOT_OWNER")] UserRoomNotOwner = 1008,
  /// <summary>
  ///game 1101~1200
  /// </summary>
  [pbr::OriginalName("GAME_ANCHOR_STATUS_ERROR")] GameAnchorStatusError = 1101,
  /// <summary>
  ///房间号有误
  /// </summary>
  [pbr::OriginalName("GAME_ROOM_ERROR")] GameRoomError = 1102,
  /// <summary>
  ///玩家加入游戏
  /// </summary>
  [pbr::OriginalName("GAME_USER_NOTIN")] GameUserNotin = 1103,
  /// <summary>
  ///玩家胜场不足
  /// </summary>
  [pbr::OriginalName("GAME_USER_WIN_NOT_ENOUGH")] GameUserWinNotEnough = 1104,
  /// <summary>
  ///钓鱼模式不存在
  /// </summary>
  [pbr::OriginalName("LUCK_MODE_NOT_EXIST")] LuckModeNotExist = 1105,
  /// <summary>
  ///主播金额不够
  /// </summary>
  [pbr::OriginalName("GAME_MONEY_NOT_ENOUGH")] GameMoneyNotEnough = 1106,
  /// <summary>
  ///失鱼招领次数不够
  /// </summary>
  [pbr::OriginalName("GAME_CATCH_FISH_NOT_ENOUGH")] GameCatchFishNotEnough = 1107,
  /// <summary>
  ///dy  1201~1300
  /// </summary>
  [pbr::OriginalName("DY_ERROR")] DyError = 1201,
  /// <summary>
  /// 获取抖音直播间信息错误
  /// </summary>
  [pbr::OriginalName("DY_WEBCAST_ERROR")] DyWebcastError = 1202,
  /// <summary>
  ///task  1301~1400
  /// </summary>
  [pbr::OriginalName("TASK_STATUS_ERROR")] TaskStatusError = 1301,
}

#endregion


#endregion Designer generated code
