// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: XOGame.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from XOGame.proto</summary>
public static partial class XOGameReflection {

  #region Descriptor
  /// <summary>File descriptor for XOGame.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static XOGameReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgxYT0dhbWUucHJvdG8aFVhPQ29tbW9uTWVzc2FnZS5wcm90byIsCg5DMlNf",
          "R2FtZV9TdGFydBIRCgR0aW1lGAIgASgDSACIAQFCBwoFX3RpbWUiNAoOUzJD",
          "X0dhbWVfU3RhcnQSFQoIcm91bmROdW0YASABKAlIAIgBAUILCglfcm91bmRO",
          "dW0irgEKD0MyU19HYW1lX1JlY29yZBIWCglzY29yZVBvb2wYASABKANIAIgB",
          "ARIYCgtzY29yZVJlbWFpbhgCIAEoA0gBiAEBEhEKCXBvaW50UG9vbBgDIAMo",
          "AxIQCgN3aW4YBCABKAVIAogBARIeCgh1c2VyUmFuaxgKIAMoCzIMLlVzZXJS",
          "YW5rRHRvQgwKCl9zY29yZVBvb2xCDgoMX3Njb3JlUmVtYWluQgYKBF93aW4i",
          "kwIKD1MyQ19HYW1lX1JlY29yZBIWCglzY29yZVBvb2wYASABKANIAIgBARIa",
          "Cg1zY29yZVBvb2xTaG93GAIgASgDSAGIAQESGgoNcG9pbnRQb29sU2hvdxgD",
          "IAEoA0gCiAEBEiQKCHVzZXJSYW5rGAogAygLMhIuVXNlclJhbmtEZXRhaWxE",
          "dG8SGQoMdXNlcklkV2luTVZQGAsgASgFSAOIAQESGgoNdXNlcklkRmFpbE1W",
          "UBgMIAEoBUgEiAEBQgwKCl9zY29yZVBvb2xCEAoOX3Njb3JlUG9vbFNob3dC",
          "EAoOX3BvaW50UG9vbFNob3dCDwoNX3VzZXJJZFdpbk1WUEIQCg5fdXNlcklk",
          "RmFpbE1WUCIxChNDMlNfR2FtZV9SYW5rX1F1ZXJ5EhEKBHR5cGUYASABKAVI",
          "AIgBAUIHCgVfdHlwZSKjAQoTUzJDX0dhbWVfUmFua19RdWVyeRIRCgR0eXBl",
          "GAEgASgFSACIAQESJAoId2Vla1JhbmsYAiADKAsyEi5Vc2VyUmFua0RldGFp",
          "bER0bxIlCgltb250aFJhbmsYAyADKAsyEi5Vc2VyUmFua0RldGFpbER0bxIj",
          "Cgd3aW5SYW5rGAQgAygLMhIuVXNlclJhbmtEZXRhaWxEdG9CBwoFX3R5cGUi",
          "MQoTUzJDX0dhbWVfUGF5bG9hZEJybxIaCgZwbGF5ZXIYASADKAsyCi5QbGF5",
          "ZXJEdG9CHwoUY29tLnR3eC5vcmlnaW4ucHJvdG9CB0dhbWVBcGliBnByb3Rv",
          "Mw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::XOProto.XOCommonMessageReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::C2S_Game_Start), global::C2S_Game_Start.Parser, new[]{ "Time" }, new[]{ "Time" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::S2C_Game_Start), global::S2C_Game_Start.Parser, new[]{ "RoundNum" }, new[]{ "RoundNum" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::C2S_Game_Record), global::C2S_Game_Record.Parser, new[]{ "ScorePool", "ScoreRemain", "PointPool", "Win", "UserRank" }, new[]{ "ScorePool", "ScoreRemain", "Win" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::S2C_Game_Record), global::S2C_Game_Record.Parser, new[]{ "ScorePool", "ScorePoolShow", "PointPoolShow", "UserRank", "UserIdWinMVP", "UserIdFailMVP" }, new[]{ "ScorePool", "ScorePoolShow", "PointPoolShow", "UserIdWinMVP", "UserIdFailMVP" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::C2S_Game_Rank_Query), global::C2S_Game_Rank_Query.Parser, new[]{ "Type" }, new[]{ "Type" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::S2C_Game_Rank_Query), global::S2C_Game_Rank_Query.Parser, new[]{ "Type", "WeekRank", "MonthRank", "WinRank" }, new[]{ "Type" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::S2C_Game_PayloadBro), global::S2C_Game_PayloadBro.Parser, new[]{ "Player" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
///开始游戏
/// </summary>
public sealed partial class C2S_Game_Start : pb::IMessage<C2S_Game_Start>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<C2S_Game_Start> _parser = new pb::MessageParser<C2S_Game_Start>(() => new C2S_Game_Start());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<C2S_Game_Start> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::XOGameReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public C2S_Game_Start() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public C2S_Game_Start(C2S_Game_Start other) : this() {
    _hasBits0 = other._hasBits0;
    time_ = other.time_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public C2S_Game_Start Clone() {
    return new C2S_Game_Start(this);
  }

  /// <summary>Field number for the "time" field.</summary>
  public const int TimeFieldNumber = 2;
  private long time_;
  /// <summary>
  /// 游戏时间
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Time {
    get { if ((_hasBits0 & 1) != 0) { return time_; } else { return 0L; } }
    set {
      _hasBits0 |= 1;
      time_ = value;
    }
  }
  /// <summary>Gets whether the "time" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasTime {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "time" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearTime() {
    _hasBits0 &= ~1;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as C2S_Game_Start);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(C2S_Game_Start other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Time != other.Time) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasTime) hash ^= Time.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasTime) {
      output.WriteRawTag(16);
      output.WriteInt64(Time);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasTime) {
      output.WriteRawTag(16);
      output.WriteInt64(Time);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasTime) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Time);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(C2S_Game_Start other) {
    if (other == null) {
      return;
    }
    if (other.HasTime) {
      Time = other.Time;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 16: {
          Time = input.ReadInt64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 16: {
          Time = input.ReadInt64();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class S2C_Game_Start : pb::IMessage<S2C_Game_Start>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<S2C_Game_Start> _parser = new pb::MessageParser<S2C_Game_Start>(() => new S2C_Game_Start());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<S2C_Game_Start> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::XOGameReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public S2C_Game_Start() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public S2C_Game_Start(S2C_Game_Start other) : this() {
    roundNum_ = other.roundNum_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public S2C_Game_Start Clone() {
    return new S2C_Game_Start(this);
  }

  /// <summary>Field number for the "roundNum" field.</summary>
  public const int RoundNumFieldNumber = 1;
  private string roundNum_;
  /// <summary>
  ///一轮游戏的唯一标识
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string RoundNum {
    get { return roundNum_ ?? ""; }
    set {
      roundNum_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "roundNum" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasRoundNum {
    get { return roundNum_ != null; }
  }
  /// <summary>Clears the value of the "roundNum" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearRoundNum() {
    roundNum_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as S2C_Game_Start);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(S2C_Game_Start other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (RoundNum != other.RoundNum) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasRoundNum) hash ^= RoundNum.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasRoundNum) {
      output.WriteRawTag(10);
      output.WriteString(RoundNum);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasRoundNum) {
      output.WriteRawTag(10);
      output.WriteString(RoundNum);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasRoundNum) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(RoundNum);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(S2C_Game_Start other) {
    if (other == null) {
      return;
    }
    if (other.HasRoundNum) {
      RoundNum = other.RoundNum;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          RoundNum = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          RoundNum = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
///结束战绩上报
/// </summary>
public sealed partial class C2S_Game_Record : pb::IMessage<C2S_Game_Record>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<C2S_Game_Record> _parser = new pb::MessageParser<C2S_Game_Record>(() => new C2S_Game_Record());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<C2S_Game_Record> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::XOGameReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public C2S_Game_Record() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public C2S_Game_Record(C2S_Game_Record other) : this() {
    _hasBits0 = other._hasBits0;
    scorePool_ = other.scorePool_;
    scoreRemain_ = other.scoreRemain_;
    pointPool_ = other.pointPool_.Clone();
    win_ = other.win_;
    userRank_ = other.userRank_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public C2S_Game_Record Clone() {
    return new C2S_Game_Record(this);
  }

  /// <summary>Field number for the "scorePool" field.</summary>
  public const int ScorePoolFieldNumber = 1;
  private long scorePool_;
  /// <summary>
  /// 积分池积分
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long ScorePool {
    get { if ((_hasBits0 & 1) != 0) { return scorePool_; } else { return 0L; } }
    set {
      _hasBits0 |= 1;
      scorePool_ = value;
    }
  }
  /// <summary>Gets whether the "scorePool" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasScorePool {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "scorePool" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearScorePool() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "scoreRemain" field.</summary>
  public const int ScoreRemainFieldNumber = 2;
  private long scoreRemain_;
  /// <summary>
  /// 剩余积分 (场上还剩余的单位)
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long ScoreRemain {
    get { if ((_hasBits0 & 2) != 0) { return scoreRemain_; } else { return 0L; } }
    set {
      _hasBits0 |= 2;
      scoreRemain_ = value;
    }
  }
  /// <summary>Gets whether the "scoreRemain" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasScoreRemain {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "scoreRemain" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearScoreRemain() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "pointPool" field.</summary>
  public const int PointPoolFieldNumber = 3;
  private static readonly pb::FieldCodec<long> _repeated_pointPool_codec
      = pb::FieldCodec.ForInt64(26);
  private readonly pbc::RepeatedField<long> pointPool_ = new pbc::RepeatedField<long>();
  /// <summary>
  /// 胜点积分池
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<long> PointPool {
    get { return pointPool_; }
  }

  /// <summary>Field number for the "win" field.</summary>
  public const int WinFieldNumber = 4;
  private int win_;
  /// <summary>
  /// 获胜方 0红 1蓝
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Win {
    get { if ((_hasBits0 & 4) != 0) { return win_; } else { return 0; } }
    set {
      _hasBits0 |= 4;
      win_ = value;
    }
  }
  /// <summary>Gets whether the "win" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasWin {
    get { return (_hasBits0 & 4) != 0; }
  }
  /// <summary>Clears the value of the "win" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearWin() {
    _hasBits0 &= ~4;
  }

  /// <summary>Field number for the "userRank" field.</summary>
  public const int UserRankFieldNumber = 10;
  private static readonly pb::FieldCodec<global::XOProto.UserRankDto> _repeated_userRank_codec
      = pb::FieldCodec.ForMessage(82, global::XOProto.UserRankDto.Parser);
  private readonly pbc::RepeatedField<global::XOProto.UserRankDto> userRank_ = new pbc::RepeatedField<global::XOProto.UserRankDto>();
  /// <summary>
  /// 局内玩家得分信息
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::XOProto.UserRankDto> UserRank {
    get { return userRank_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as C2S_Game_Record);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(C2S_Game_Record other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ScorePool != other.ScorePool) return false;
    if (ScoreRemain != other.ScoreRemain) return false;
    if(!pointPool_.Equals(other.pointPool_)) return false;
    if (Win != other.Win) return false;
    if(!userRank_.Equals(other.userRank_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasScorePool) hash ^= ScorePool.GetHashCode();
    if (HasScoreRemain) hash ^= ScoreRemain.GetHashCode();
    hash ^= pointPool_.GetHashCode();
    if (HasWin) hash ^= Win.GetHashCode();
    hash ^= userRank_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasScorePool) {
      output.WriteRawTag(8);
      output.WriteInt64(ScorePool);
    }
    if (HasScoreRemain) {
      output.WriteRawTag(16);
      output.WriteInt64(ScoreRemain);
    }
    pointPool_.WriteTo(output, _repeated_pointPool_codec);
    if (HasWin) {
      output.WriteRawTag(32);
      output.WriteInt32(Win);
    }
    userRank_.WriteTo(output, _repeated_userRank_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasScorePool) {
      output.WriteRawTag(8);
      output.WriteInt64(ScorePool);
    }
    if (HasScoreRemain) {
      output.WriteRawTag(16);
      output.WriteInt64(ScoreRemain);
    }
    pointPool_.WriteTo(ref output, _repeated_pointPool_codec);
    if (HasWin) {
      output.WriteRawTag(32);
      output.WriteInt32(Win);
    }
    userRank_.WriteTo(ref output, _repeated_userRank_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasScorePool) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(ScorePool);
    }
    if (HasScoreRemain) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(ScoreRemain);
    }
    size += pointPool_.CalculateSize(_repeated_pointPool_codec);
    if (HasWin) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Win);
    }
    size += userRank_.CalculateSize(_repeated_userRank_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(C2S_Game_Record other) {
    if (other == null) {
      return;
    }
    if (other.HasScorePool) {
      ScorePool = other.ScorePool;
    }
    if (other.HasScoreRemain) {
      ScoreRemain = other.ScoreRemain;
    }
    pointPool_.Add(other.pointPool_);
    if (other.HasWin) {
      Win = other.Win;
    }
    userRank_.Add(other.userRank_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          ScorePool = input.ReadInt64();
          break;
        }
        case 16: {
          ScoreRemain = input.ReadInt64();
          break;
        }
        case 26:
        case 24: {
          pointPool_.AddEntriesFrom(input, _repeated_pointPool_codec);
          break;
        }
        case 32: {
          Win = input.ReadInt32();
          break;
        }
        case 82: {
          userRank_.AddEntriesFrom(input, _repeated_userRank_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          ScorePool = input.ReadInt64();
          break;
        }
        case 16: {
          ScoreRemain = input.ReadInt64();
          break;
        }
        case 26:
        case 24: {
          pointPool_.AddEntriesFrom(ref input, _repeated_pointPool_codec);
          break;
        }
        case 32: {
          Win = input.ReadInt32();
          break;
        }
        case 82: {
          userRank_.AddEntriesFrom(ref input, _repeated_userRank_codec);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class S2C_Game_Record : pb::IMessage<S2C_Game_Record>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<S2C_Game_Record> _parser = new pb::MessageParser<S2C_Game_Record>(() => new S2C_Game_Record());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<S2C_Game_Record> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::XOGameReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public S2C_Game_Record() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public S2C_Game_Record(S2C_Game_Record other) : this() {
    _hasBits0 = other._hasBits0;
    scorePool_ = other.scorePool_;
    scorePoolShow_ = other.scorePoolShow_;
    pointPoolShow_ = other.pointPoolShow_;
    userRank_ = other.userRank_.Clone();
    userIdWinMVP_ = other.userIdWinMVP_;
    userIdFailMVP_ = other.userIdFailMVP_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public S2C_Game_Record Clone() {
    return new S2C_Game_Record(this);
  }

  /// <summary>Field number for the "scorePool" field.</summary>
  public const int ScorePoolFieldNumber = 1;
  private long scorePool_;
  /// <summary>
  /// 积分池剩余总积分
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long ScorePool {
    get { if ((_hasBits0 & 1) != 0) { return scorePool_; } else { return 0L; } }
    set {
      _hasBits0 |= 1;
      scorePool_ = value;
    }
  }
  /// <summary>Gets whether the "scorePool" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasScorePool {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "scorePool" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearScorePool() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "scorePoolShow" field.</summary>
  public const int ScorePoolShowFieldNumber = 2;
  private long scorePoolShow_;
  /// <summary>
  /// 积分池 展示用
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long ScorePoolShow {
    get { if ((_hasBits0 & 2) != 0) { return scorePoolShow_; } else { return 0L; } }
    set {
      _hasBits0 |= 2;
      scorePoolShow_ = value;
    }
  }
  /// <summary>Gets whether the "scorePoolShow" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasScorePoolShow {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "scorePoolShow" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearScorePoolShow() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "pointPoolShow" field.</summary>
  public const int PointPoolShowFieldNumber = 3;
  private long pointPoolShow_;
  /// <summary>
  /// 胜点池 展示用
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long PointPoolShow {
    get { if ((_hasBits0 & 4) != 0) { return pointPoolShow_; } else { return 0L; } }
    set {
      _hasBits0 |= 4;
      pointPoolShow_ = value;
    }
  }
  /// <summary>Gets whether the "pointPoolShow" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasPointPoolShow {
    get { return (_hasBits0 & 4) != 0; }
  }
  /// <summary>Clears the value of the "pointPoolShow" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearPointPoolShow() {
    _hasBits0 &= ~4;
  }

  /// <summary>Field number for the "userRank" field.</summary>
  public const int UserRankFieldNumber = 10;
  private static readonly pb::FieldCodec<global::XOProto.UserRankDetailDto> _repeated_userRank_codec
      = pb::FieldCodec.ForMessage(82, global::XOProto.UserRankDetailDto.Parser);
  private readonly pbc::RepeatedField<global::XOProto.UserRankDetailDto> userRank_ = new pbc::RepeatedField<global::XOProto.UserRankDetailDto>();
  /// <summary>
  /// 本局结算人员信息
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::XOProto.UserRankDetailDto> UserRank {
    get { return userRank_; }
  }

  /// <summary>Field number for the "userIdWinMVP" field.</summary>
  public const int UserIdWinMVPFieldNumber = 11;
  private int userIdWinMVP_;
  /// <summary>
  ///胜方MVP
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int UserIdWinMVP {
    get { if ((_hasBits0 & 8) != 0) { return userIdWinMVP_; } else { return 0; } }
    set {
      _hasBits0 |= 8;
      userIdWinMVP_ = value;
    }
  }
  /// <summary>Gets whether the "userIdWinMVP" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasUserIdWinMVP {
    get { return (_hasBits0 & 8) != 0; }
  }
  /// <summary>Clears the value of the "userIdWinMVP" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearUserIdWinMVP() {
    _hasBits0 &= ~8;
  }

  /// <summary>Field number for the "userIdFailMVP" field.</summary>
  public const int UserIdFailMVPFieldNumber = 12;
  private int userIdFailMVP_;
  /// <summary>
  ///败方MVP
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int UserIdFailMVP {
    get { if ((_hasBits0 & 16) != 0) { return userIdFailMVP_; } else { return 0; } }
    set {
      _hasBits0 |= 16;
      userIdFailMVP_ = value;
    }
  }
  /// <summary>Gets whether the "userIdFailMVP" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasUserIdFailMVP {
    get { return (_hasBits0 & 16) != 0; }
  }
  /// <summary>Clears the value of the "userIdFailMVP" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearUserIdFailMVP() {
    _hasBits0 &= ~16;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as S2C_Game_Record);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(S2C_Game_Record other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ScorePool != other.ScorePool) return false;
    if (ScorePoolShow != other.ScorePoolShow) return false;
    if (PointPoolShow != other.PointPoolShow) return false;
    if(!userRank_.Equals(other.userRank_)) return false;
    if (UserIdWinMVP != other.UserIdWinMVP) return false;
    if (UserIdFailMVP != other.UserIdFailMVP) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasScorePool) hash ^= ScorePool.GetHashCode();
    if (HasScorePoolShow) hash ^= ScorePoolShow.GetHashCode();
    if (HasPointPoolShow) hash ^= PointPoolShow.GetHashCode();
    hash ^= userRank_.GetHashCode();
    if (HasUserIdWinMVP) hash ^= UserIdWinMVP.GetHashCode();
    if (HasUserIdFailMVP) hash ^= UserIdFailMVP.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasScorePool) {
      output.WriteRawTag(8);
      output.WriteInt64(ScorePool);
    }
    if (HasScorePoolShow) {
      output.WriteRawTag(16);
      output.WriteInt64(ScorePoolShow);
    }
    if (HasPointPoolShow) {
      output.WriteRawTag(24);
      output.WriteInt64(PointPoolShow);
    }
    userRank_.WriteTo(output, _repeated_userRank_codec);
    if (HasUserIdWinMVP) {
      output.WriteRawTag(88);
      output.WriteInt32(UserIdWinMVP);
    }
    if (HasUserIdFailMVP) {
      output.WriteRawTag(96);
      output.WriteInt32(UserIdFailMVP);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasScorePool) {
      output.WriteRawTag(8);
      output.WriteInt64(ScorePool);
    }
    if (HasScorePoolShow) {
      output.WriteRawTag(16);
      output.WriteInt64(ScorePoolShow);
    }
    if (HasPointPoolShow) {
      output.WriteRawTag(24);
      output.WriteInt64(PointPoolShow);
    }
    userRank_.WriteTo(ref output, _repeated_userRank_codec);
    if (HasUserIdWinMVP) {
      output.WriteRawTag(88);
      output.WriteInt32(UserIdWinMVP);
    }
    if (HasUserIdFailMVP) {
      output.WriteRawTag(96);
      output.WriteInt32(UserIdFailMVP);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasScorePool) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(ScorePool);
    }
    if (HasScorePoolShow) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(ScorePoolShow);
    }
    if (HasPointPoolShow) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(PointPoolShow);
    }
    size += userRank_.CalculateSize(_repeated_userRank_codec);
    if (HasUserIdWinMVP) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(UserIdWinMVP);
    }
    if (HasUserIdFailMVP) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(UserIdFailMVP);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(S2C_Game_Record other) {
    if (other == null) {
      return;
    }
    if (other.HasScorePool) {
      ScorePool = other.ScorePool;
    }
    if (other.HasScorePoolShow) {
      ScorePoolShow = other.ScorePoolShow;
    }
    if (other.HasPointPoolShow) {
      PointPoolShow = other.PointPoolShow;
    }
    userRank_.Add(other.userRank_);
    if (other.HasUserIdWinMVP) {
      UserIdWinMVP = other.UserIdWinMVP;
    }
    if (other.HasUserIdFailMVP) {
      UserIdFailMVP = other.UserIdFailMVP;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          ScorePool = input.ReadInt64();
          break;
        }
        case 16: {
          ScorePoolShow = input.ReadInt64();
          break;
        }
        case 24: {
          PointPoolShow = input.ReadInt64();
          break;
        }
        case 82: {
          userRank_.AddEntriesFrom(input, _repeated_userRank_codec);
          break;
        }
        case 88: {
          UserIdWinMVP = input.ReadInt32();
          break;
        }
        case 96: {
          UserIdFailMVP = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          ScorePool = input.ReadInt64();
          break;
        }
        case 16: {
          ScorePoolShow = input.ReadInt64();
          break;
        }
        case 24: {
          PointPoolShow = input.ReadInt64();
          break;
        }
        case 82: {
          userRank_.AddEntriesFrom(ref input, _repeated_userRank_codec);
          break;
        }
        case 88: {
          UserIdWinMVP = input.ReadInt32();
          break;
        }
        case 96: {
          UserIdFailMVP = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class C2S_Game_Rank_Query : pb::IMessage<C2S_Game_Rank_Query>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<C2S_Game_Rank_Query> _parser = new pb::MessageParser<C2S_Game_Rank_Query>(() => new C2S_Game_Rank_Query());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<C2S_Game_Rank_Query> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::XOGameReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public C2S_Game_Rank_Query() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public C2S_Game_Rank_Query(C2S_Game_Rank_Query other) : this() {
    _hasBits0 = other._hasBits0;
    type_ = other.type_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public C2S_Game_Rank_Query Clone() {
    return new C2S_Game_Rank_Query(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private int type_;
  /// <summary>
  /// 0:所有 1玩家周榜  2玩家月榜 3连胜榜
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Type {
    get { if ((_hasBits0 & 1) != 0) { return type_; } else { return 0; } }
    set {
      _hasBits0 |= 1;
      type_ = value;
    }
  }
  /// <summary>Gets whether the "type" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasType {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "type" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearType() {
    _hasBits0 &= ~1;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as C2S_Game_Rank_Query);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(C2S_Game_Rank_Query other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasType) hash ^= Type.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasType) {
      output.WriteRawTag(8);
      output.WriteInt32(Type);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasType) {
      output.WriteRawTag(8);
      output.WriteInt32(Type);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasType) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Type);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(C2S_Game_Rank_Query other) {
    if (other == null) {
      return;
    }
    if (other.HasType) {
      Type = other.Type;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Type = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Type = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class S2C_Game_Rank_Query : pb::IMessage<S2C_Game_Rank_Query>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<S2C_Game_Rank_Query> _parser = new pb::MessageParser<S2C_Game_Rank_Query>(() => new S2C_Game_Rank_Query());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<S2C_Game_Rank_Query> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::XOGameReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public S2C_Game_Rank_Query() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public S2C_Game_Rank_Query(S2C_Game_Rank_Query other) : this() {
    _hasBits0 = other._hasBits0;
    type_ = other.type_;
    weekRank_ = other.weekRank_.Clone();
    monthRank_ = other.monthRank_.Clone();
    winRank_ = other.winRank_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public S2C_Game_Rank_Query Clone() {
    return new S2C_Game_Rank_Query(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private int type_;
  /// <summary>
  /// 0:所有   1玩家周榜  2玩家月榜 3连胜榜
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Type {
    get { if ((_hasBits0 & 1) != 0) { return type_; } else { return 0; } }
    set {
      _hasBits0 |= 1;
      type_ = value;
    }
  }
  /// <summary>Gets whether the "type" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasType {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "type" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearType() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "weekRank" field.</summary>
  public const int WeekRankFieldNumber = 2;
  private static readonly pb::FieldCodec<global::XOProto.UserRankDetailDto> _repeated_weekRank_codec
      = pb::FieldCodec.ForMessage(18, global::XOProto.UserRankDetailDto.Parser);
  private readonly pbc::RepeatedField<global::XOProto.UserRankDetailDto> weekRank_ = new pbc::RepeatedField<global::XOProto.UserRankDetailDto>();
  /// <summary>
  /// 玩家周榜
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::XOProto.UserRankDetailDto> WeekRank {
    get { return weekRank_; }
  }

  /// <summary>Field number for the "monthRank" field.</summary>
  public const int MonthRankFieldNumber = 3;
  private static readonly pb::FieldCodec<global::XOProto.UserRankDetailDto> _repeated_monthRank_codec
      = pb::FieldCodec.ForMessage(26, global::XOProto.UserRankDetailDto.Parser);
  private readonly pbc::RepeatedField<global::XOProto.UserRankDetailDto> monthRank_ = new pbc::RepeatedField<global::XOProto.UserRankDetailDto>();
  /// <summary>
  /// 玩家月榜
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::XOProto.UserRankDetailDto> MonthRank {
    get { return monthRank_; }
  }

  /// <summary>Field number for the "winRank" field.</summary>
  public const int WinRankFieldNumber = 4;
  private static readonly pb::FieldCodec<global::XOProto.UserRankDetailDto> _repeated_winRank_codec
      = pb::FieldCodec.ForMessage(34, global::XOProto.UserRankDetailDto.Parser);
  private readonly pbc::RepeatedField<global::XOProto.UserRankDetailDto> winRank_ = new pbc::RepeatedField<global::XOProto.UserRankDetailDto>();
  /// <summary>
  /// 连胜月榜
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::XOProto.UserRankDetailDto> WinRank {
    get { return winRank_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as S2C_Game_Rank_Query);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(S2C_Game_Rank_Query other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    if(!weekRank_.Equals(other.weekRank_)) return false;
    if(!monthRank_.Equals(other.monthRank_)) return false;
    if(!winRank_.Equals(other.winRank_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasType) hash ^= Type.GetHashCode();
    hash ^= weekRank_.GetHashCode();
    hash ^= monthRank_.GetHashCode();
    hash ^= winRank_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasType) {
      output.WriteRawTag(8);
      output.WriteInt32(Type);
    }
    weekRank_.WriteTo(output, _repeated_weekRank_codec);
    monthRank_.WriteTo(output, _repeated_monthRank_codec);
    winRank_.WriteTo(output, _repeated_winRank_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasType) {
      output.WriteRawTag(8);
      output.WriteInt32(Type);
    }
    weekRank_.WriteTo(ref output, _repeated_weekRank_codec);
    monthRank_.WriteTo(ref output, _repeated_monthRank_codec);
    winRank_.WriteTo(ref output, _repeated_winRank_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasType) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Type);
    }
    size += weekRank_.CalculateSize(_repeated_weekRank_codec);
    size += monthRank_.CalculateSize(_repeated_monthRank_codec);
    size += winRank_.CalculateSize(_repeated_winRank_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(S2C_Game_Rank_Query other) {
    if (other == null) {
      return;
    }
    if (other.HasType) {
      Type = other.Type;
    }
    weekRank_.Add(other.weekRank_);
    monthRank_.Add(other.monthRank_);
    winRank_.Add(other.winRank_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Type = input.ReadInt32();
          break;
        }
        case 18: {
          weekRank_.AddEntriesFrom(input, _repeated_weekRank_codec);
          break;
        }
        case 26: {
          monthRank_.AddEntriesFrom(input, _repeated_monthRank_codec);
          break;
        }
        case 34: {
          winRank_.AddEntriesFrom(input, _repeated_winRank_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Type = input.ReadInt32();
          break;
        }
        case 18: {
          weekRank_.AddEntriesFrom(ref input, _repeated_weekRank_codec);
          break;
        }
        case 26: {
          monthRank_.AddEntriesFrom(ref input, _repeated_monthRank_codec);
          break;
        }
        case 34: {
          winRank_.AddEntriesFrom(ref input, _repeated_winRank_codec);
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// 推送客户端玩家礼物弹幕消息
/// </summary>
public sealed partial class S2C_Game_PayloadBro : pb::IMessage<S2C_Game_PayloadBro>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<S2C_Game_PayloadBro> _parser = new pb::MessageParser<S2C_Game_PayloadBro>(() => new S2C_Game_PayloadBro());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<S2C_Game_PayloadBro> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::XOGameReflection.Descriptor.MessageTypes[6]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public S2C_Game_PayloadBro() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public S2C_Game_PayloadBro(S2C_Game_PayloadBro other) : this() {
    player_ = other.player_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public S2C_Game_PayloadBro Clone() {
    return new S2C_Game_PayloadBro(this);
  }

  /// <summary>Field number for the "player" field.</summary>
  public const int PlayerFieldNumber = 1;
  private static readonly pb::FieldCodec<global::XOProto.PlayerDto> _repeated_player_codec
      = pb::FieldCodec.ForMessage(10, global::XOProto.PlayerDto.Parser);
  private readonly pbc::RepeatedField<global::XOProto.PlayerDto> player_ = new pbc::RepeatedField<global::XOProto.PlayerDto>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::XOProto.PlayerDto> Player {
    get { return player_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as S2C_Game_PayloadBro);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(S2C_Game_PayloadBro other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!player_.Equals(other.player_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= player_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    player_.WriteTo(output, _repeated_player_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    player_.WriteTo(ref output, _repeated_player_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += player_.CalculateSize(_repeated_player_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(S2C_Game_PayloadBro other) {
    if (other == null) {
      return;
    }
    player_.Add(other.player_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          player_.AddEntriesFrom(input, _repeated_player_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          player_.AddEntriesFrom(ref input, _repeated_player_codec);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
