// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: XOMain.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace XOProto {

  /// <summary>Holder for reflection information generated from XOMain.proto</summary>
  public static partial class XOMainReflection {

    #region Descriptor
    /// <summary>File descriptor for XOMain.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static XOMainReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxYT01haW4ucHJvdG8qlQUKB0VfTVNHSUQSCwoHVU5LTk9XThAAEhgKE0Vf",
            "TXNnSURfVXNlcl9DcmVhdGUQ6QcSFwoSRV9Nc2dJRF9Vc2VyX0xvZ2luEOoH",
            "EhYKEUVfTXNnSURfVXNlcl9BdXRoEOsHEhwKF0VfTXNnSURfVXNlcl9RdWlj",
            "a0xvZ2luEOwHEhsKFkVfTXNnSURfVXNlcl9Mb2dvdXRCcm8Q7QcSFwoSRV9N",
            "c2dJRF9Vc2VyX0hlYXJ0EO4HEhwKF0VfTXNnSURfVXNlcl9OYW1lQ2hhbmdl",
            "EO8HEh4KGUVfTXNnSURfVXNlcl9SZWFsTmFtZUF1dGgQ+gcSFwoSRV9Nc2dJ",
            "RF9Vc2VyX0d1aWRlEPsHEh0KGEVfTXNnSURfVXNlcl9Sb29tX0NyZWF0ZRD8",
            "BxIaChVFX01zZ0lEX1VzZXJfUm9vbV9BZGQQ/QcSGwoWRV9Nc2dJRF9Vc2Vy",
            "X1Jvb21fUXVpdBD+BxIcChdFX01zZ0lEX1VzZXJfUm9vbV9RdWVyeRD/BxId",
            "ChhFX01zZ0lEX1VzZXJfSW52aXRlX1NlbmQQgAgSHgoZRV9Nc2dJRF9Vc2Vy",
            "X0ludml0ZV9RdWVyeRCBCBIeChlFX01zZ0lEX1VzZXJfUmVhZHlfQ2hhbmdl",
            "EIIIEiAKG0VfTXNnSURfVXNlcl9Sb29tX0NoYW5nZUJybxC5CBIhChxFX01z",
            "Z0lEX1VzZXJfUmVhZHlfQ2hhbmdlQnJvELoIEhcKEkVfTXNnSURfR2FtZV9T",
            "dGFydBCxCRIcChdFX01zZ0lEX0dhbWVfUmFua19RdWVyeRCyCRIYChNFX01z",
            "Z0lEX0dhbWVfUmVjb3JkELMJEhwKF0VfTXNnSURfR2FtZV9QYXlsb2FkQnJv",
            "EIEKQicKFGNvbS50d3gub3JpZ2luLnByb3RvQgVBcGlJZKoCB1hPUHJvdG9i",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::XOProto.E_MSGID), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum E_MSGID {
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    /// <summary>
    ///用户 1001~1100  每个功能的ID 预留100个
    /// </summary>
    [pbr::OriginalName("E_MsgID_User_Create")] UserCreate = 1001,
    /// <summary>
    ///用户登录 USER_LOGIN
    /// </summary>
    [pbr::OriginalName("E_MsgID_User_Login")] UserLogin = 1002,
    [pbr::OriginalName("E_MsgID_User_Auth")] UserAuth = 1003,
    [pbr::OriginalName("E_MsgID_User_QuickLogin")] UserQuickLogin = 1004,
    /// <summary>
    ///玩家登出 通知
    /// </summary>
    [pbr::OriginalName("E_MsgID_User_LogoutBro")] UserLogoutBro = 1005,
    /// <summary>
    ///心跳应答
    /// </summary>
    [pbr::OriginalName("E_MsgID_User_Heart")] UserHeart = 1006,
    /// <summary>
    ///修改用户昵称
    /// </summary>
    [pbr::OriginalName("E_MsgID_User_NameChange")] UserNameChange = 1007,
    /// <summary>
    ///实名认证
    /// </summary>
    [pbr::OriginalName("E_MsgID_User_RealNameAuth")] UserRealNameAuth = 1018,
    /// <summary>
    ///用户引导
    /// </summary>
    [pbr::OriginalName("E_MsgID_User_Guide")] UserGuide = 1019,
    /// <summary>
    ///创房
    /// </summary>
    [pbr::OriginalName("E_MsgID_User_Room_Create")] UserRoomCreate = 1020,
    /// <summary>
    ///加入房间
    /// </summary>
    [pbr::OriginalName("E_MsgID_User_Room_Add")] UserRoomAdd = 1021,
    /// <summary>
    ///退房、踢人
    /// </summary>
    [pbr::OriginalName("E_MsgID_User_Room_Quit")] UserRoomQuit = 1022,
    /// <summary>
    ///查询房间信息
    /// </summary>
    [pbr::OriginalName("E_MsgID_User_Room_Query")] UserRoomQuery = 1023,
    /// <summary>
    ///发送邀请信息
    /// </summary>
    [pbr::OriginalName("E_MsgID_User_Invite_Send")] UserInviteSend = 1024,
    /// <summary>
    ///查询邀请信息
    /// </summary>
    [pbr::OriginalName("E_MsgID_User_Invite_Query")] UserInviteQuery = 1025,
    /// <summary>
    ///主播准备状态变化
    /// </summary>
    [pbr::OriginalName("E_MsgID_User_Ready_Change")] UserReadyChange = 1026,
    /// <summary>
    ///房间变化推送
    /// </summary>
    [pbr::OriginalName("E_MsgID_User_Room_ChangeBro")] UserRoomChangeBro = 1081,
    /// <summary>
    ///准备状态变化推送
    /// </summary>
    [pbr::OriginalName("E_MsgID_User_Ready_ChangeBro")] UserReadyChangeBro = 1082,
    /// <summary>
    ///游戏  1201~1300
    /// </summary>
    [pbr::OriginalName("E_MsgID_Game_Start")] GameStart = 1201,
    /// <summary>
    ///游戏排行榜查询
    /// </summary>
    [pbr::OriginalName("E_MsgID_Game_Rank_Query")] GameRankQuery = 1202,
    /// <summary>
    ///游戏战绩上报 游戏结束
    /// </summary>
    [pbr::OriginalName("E_MsgID_Game_Record")] GameRecord = 1203,
    /// <summary>
    ///抖音数据推送
    /// </summary>
    [pbr::OriginalName("E_MsgID_Game_PayloadBro")] GamePayloadBro = 1281,
  }

  #endregion

}

#endregion Designer generated code
